Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  EnforcedStyle: never

Style/ClassAndModuleChildren:
  Enabled: false

Metrics/LineLength:
  Max: 225

Metrics/MethodLength:
  Max: 30

Metrics/BlockLength:
  Max: 150

Metrics/AbcSize:
  Max: 80

Metrics/CyclomaticComplexity:
  Max: 20

Metrics/PerceivedComplexity:
  Max: 20
